apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pj8tyrxtt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pj8tyrxtt-python 
  name: pj8tyrxtt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pj8tyrxtt-python 
